# naming conventions:
#   - volume names SHOULD end by "_db"
#   - services CAN have full name
#   - every service/volume/network name SHOULD be lowercase
#   - any hidden service/volume/network SHOULD be named in a different way (e.g.: ".servicename")


# notices:
#   - EVERY service MUST depend on the logger
#   - EVERY service CAN access common_tools



# sample volume
  # logger:
  #   driver: local
  #   name: logger
  #   driver_opts:
  #     o: bind
  #     device: /home/leonardo/data/logger
  #     type: none


# sample container: receiver
  # receiver:																# container
  #   container_name: receiver							# coniainer name (alias)
  #   build: ./requirements/receiver				# Dockerfile directory
  #   image: mariadb:42
  #   depends_on:														# container is built after ...
  #     - logger
  #   networks:															# connected to networks ...
  #     - app-network
  #   env_file:															# path to .env
  #     - .env
  #   volumes:															# accessible volumes
  #     - wp:/var/www/html
  #   ports:																# communication ports with outer environment
  #     - "443:443"
  #   command: ["bash", "echo"]							# execute a command outside (?) container
  #   restart: always												# in case of crash restarts service


version: "3.5"

networks:
  app-network:
    name: app-network
    driver: bridge


volumes:

  common_tools:
    driver: local
    name: ct
    driver_opts:
      o: bind
      device: ./srcs/common_tools/tools
      type: none


services:

  postgres:                                            # database service
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./srcs/common_tools/tools:/var/commond
    networks:
      - app-network
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  receiver:                                             # net open service. Creates gateways
    image: ruby:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./srcs/common_tools/tools:/var/common
      - ./srcs/receiver:/var/www
    depends_on:
      - postgres
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "8008:8008"
    entrypoint: /var/www/init.sh
    working_dir: /var/www

  request_manager:
    image: ruby:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./srcs/common_tools/tools:/var/common
      - ./srcs/request_manager:/var/www
    depends_on:
      - receiver
      - postgres
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "9000:9000"
    entrypoint: /var/www/init.sh
    working_dir: /var/www

  auth:
    image: ruby:latest
    restart: always
    volumes:
      - ./srcs/common_tools/tools:/var/common
      - ./srcs/auth:/var/www
    depends_on:
      - postgres
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "9292:9292"
    entrypoint: /var/www/init.sh
    working_dir: /var/www

  tokenizer:
    image: ruby:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./srcs/common_tools/tools:/var/common
      - ./srcs/tokenizer:/var/www
    depends_on:
      - postgres
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "7890:7890"
    entrypoint: /var/www/init.sh
    working_dir: /var/www

  user_manager:
    image: ruby:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./srcs/common_tools/tools:/var/common
      - ./srcs/user_manager:/var/www
    depends_on:
      - postgres
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "7080:7080"
    entrypoint: /var/www/init.sh
    working_dir: /var/www
